### ISSUE TITLE
Error on multiple request: "possible EventEmitter memory leak detected"

### ISSUE THREAD

**Issue by wachunei** [blakeembrey/popsicle#10]
I'm using one request to get cookies from a `POST` , oncee set, I'm making another one, but then I get this error:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:160:15)
    at Request.start (/Users/wachunei/Desktop/D/testvm/node_modules/popsicle/node_modules/request/request.js:947:8)
    at Request.end (/Users/wachunei/Desktop/D/testvm/node_modules/popsicle/node_modules/request/request.js:1732:10)
    at end (/Users/wachunei/Desktop/D/testvm/node_modules/popsicle/node_modules/request/request.js:704:14)
    at Object._onImmediate (/Users/wachunei/Desktop/D/testvm/node_modules/popsicle/node_modules/request/request.js:718:7)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by blakeembrey** [comment]
@wachunei Do you have some example code? I am listening to a bunch under node (for progress), but it's not hitting 10.

**Comment by wachunei** [comment]
Actually it is something like this
```
request(parametersObject).then(function(res) {
  // do stuff
  request(anotherParameterObject).then(function(res)){
      // do stuff but you don't reach this point
    });
});

**Comment by blakeembrey** [comment]
@wachunei Interesting. What node version (`node -v`)?

**Comment by wachunei** [comment]
Pretty sure the latest stable release (I ran `brew upgrade node` this morning)

**Comment by wachunei** [comment]
0.10.36 actually

**Comment by blakeembrey** [comment]
@wachunei So I tried with something similar, but it's not replicating:

```js
if (!global.Promise) {
  require('es6-promise').polyfill();
}

var request = require('popsicle');

request('http://facebook.com')
  .then(function (res) {
    console.log('fb', res.status);
  });

request('http://google.com')
  .then(function (res) {
    console.log('google', res.status);

    return request('http://github.com');
  })
  .then(function (res) {
    console.log('github', res.status);
  });
```

**Comment by wachunei** [comment]
@blakeembrey It also works for me, it must be something I am doing wrong in my code. Any chance to share it to you privately?

**Comment by blakeembrey** [comment]
@wachunei Of course, however you want to share it. Feel free to email me directly at `hello <at> blakeembrey <dot> com` :smile:

**Comment by blakeembrey** [comment]
Ok, I'm reviewing this now and seeing what I can tidy up. I'll let you know when there's an update you might be able to test :+1:

**Comment by blakeembrey** [comment]
@wachunei So it's a multi-layered issue. You're stuck in a redirect loop (I might be able to override the default `request` behaviour here and make it work for you) and the `request` library actually adds a new listener on every redirect. Hence, 10 redirects in you hit the limit and it breaks. I'm going to do a couple of PRs now to see what we can fix in both libraries.

**Comment by blakeembrey** [comment]
OK, I emailed you back a solution that'll work for now and I'm going to close this. It still links to the core issue opened against `request`.
