### ISSUE TITLE
Make progress optional

### ISSUE THREAD

**Issue by mcasimir** [blakeembrey/popsicle#11]
Webkit is reporting `Refused to get unsafe header "Content-Length"` at each call

Awesome work anyway!

**Comment by blakeembrey** [comment]
Oh, interesting. We should definitely catch that. Is it a a CORS request? I can't think of when it'd be happening otherwise? Is it an error or a log in the console?

**Comment by blakeembrey** [comment]
@mcasimir Fixed and publish with `v0.3.11`
