### ISSUE TITLE
Missed semicolon

### ISSUE THREAD

**Issue by atomsfat** [blakeembrey/popsicle#12]
Hi, 
I think you miss a semicolon in the following line 
https://github.com/blakeembrey/popsicle/blob/master/popsicle.js#L1383
and it's a problem is somebody concat this with other libraries.

**Comment by blakeembrey** [comment]
@atomsfat It's valid to omit the semicolon in most regards (http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding) and if you're doing minification you might want to concat files using a semicolon instead of newlines.

**Comment by atomsfat** [comment]
thanks for the tip.
