### ISSUE TITLE
where is the cookie jar set to requests?

### ISSUE THREAD

**Issue by maraoz** [blakeembrey/popsicle#24]
I'm having problems with the cookie jar not working (cookies are not persisted through redirects in a GET call).
I'm reading through the code, and I couldn't find where the jar variable is set to the request instance. I'm trying to debug what I'm doing wrong. 

I'm doing this:
```js
  this.cookies = popsicle.jar()
  this.request = popsicle.defaults({
    options: { jar: this.cookies }
  })
```

and then doing the request like so:
```js
  this.request.get({
    url: this.info.url,
  })
  .then((response) => {
    var fs = require('fs');
    fs.writeFileSync('output.html', response.body)
  })

```
The URL I'm GETting redirects 2 times, setting cookies. 
But from the result and debugging the requests, the cookies are not being set and sent in the 2nd and 3rd requests. 
I've been following the `jar` option down to https://github.com/blakeembrey/popsicle/blob/v1.2.1/lib/base.ts#L46 and it doesn't seem to be set. Could it be that it's not set, or that I'm doing something wrong? Could you point to the line where the jar option is set?

Thanks for your time!

**Comment by blakeembrey** [comment]
You're absolutely correct, sorry. It's currently a plugin (https://github.com/blakeembrey/popsicle/blob/master/lib/plugins/index.ts) and plugins are only being run pre and post request. I'll either have to move `jar` into "core" or rethink how plugins interact with redirects.

**Comment by maraoz** [comment]
Ahhh, that explains it! I'll try to setup development for popsicle and fix it. If I can do it I'll submit a PR in case you're interested.
Thanks for the great lib anyway! :)

**Comment by blakeembrey** [comment]
I'm definitely interested in a PR :+1: This is a pretty critical issue.

**Comment by blakeembrey** [comment]
It's either a matter of making the node requests go through the middleware API (not sure how tricky this will be, might not be too bad but it'll require a few parts of the code to change and/or be exposed) or make the jar option handled as part of the redirect flow and remove it from being a plugin. I, personally, would probably go for the second option - much simpler and it still makes sense semantically (the request logic is node only, so node only options can be used).

**Comment by maraoz** [comment]
Thanks. Will try that. I'm new to TypeScript, so I might drop this and use another lib if it takes too long. Will let you know. :)
