### ISSUE TITLE
Use typings instead of TSD

### ISSUE THREAD

**Issue by blakeembrey** [blakeembrey/popsicle#29]
https://github.com/typings/typings

**Comment by jocull** [comment]
Just curious, but why typings over tsd?

**Comment by blakeembrey** [comment]
Pretty much for the reasons I recently wrote up in the README: https://github.com/typings/typings#why. I spent a long time trying to fix or otherwise patch the issues with DefinitelyTyped and TSD, but eventually decided it wasn't worth the time investment and I released the things I was doing as a rewrite of TSD as `typings`. Since it's completely incompatible with all of DT, `typings` exists outside of DT for now.

**Comment by jocull** [comment]
:+1: I went looking for definitions in both TSD and typings without luck. Should be able to put together definitions in the meantime from the npm module :)

**Comment by blakeembrey** [comment]
For popsicle, you mean? It's written in TypeScript already.

**Comment by blakeembrey** [comment]
The reason that the type definition won't work is exactly why I had to release `typings`, since ambient module declarations (E.g. the ones in `src/typings`) will conflict with things in DT. I'll fix this up to use `typings` ASAP if you need the type definition for this module :+1:

**Comment by blakeembrey** [comment]
By the way (sorry for the spam) but if you want to contribute to typings it would be greatly appreciated :smile: It's only a small registry right now, DT still has a few years on `typings`, but it shouldn't take long to catch up.

**Comment by jocull** [comment]
Generally, `node_modules` is excluded from our TS build process and we reference the definitions from TSD instead. I'm not exactly sure how to reference them in this case. For the short term, perhaps we'll build `popsicle` from sources to keep the TS definitions straight. I'm not crazy about TSD by any means, but it sure beats cloning stuff out of the DT repo manually!

**Comment by blakeembrey** [comment]
Ok, I'd love to learn more about what you're doing some time. I'll ping you when I update this to use `typings`, but using TSD with this project is impossible (as is DT) because of the ambient module nature of DT. When you use typings, it's just `npm:popsicle`. 

What will you do for now? Copy the definitions out of this repo, wrap them in an ambient module and push them on DT to install? I sadly had to do that for `typings` itself (since typings uses popsicle, and obviously didn't exist itself yet).

**Comment by jocull** [comment]
I'm trying to use `typings` right now, but having too much trouble. I'm not sure I understand how it determines what to pull all the way. I realize this is all early days, so just trying to keep you in the loop for what I'm running into.

```
$ typings install npm:popsicle
>> Error: Unable to resolve node_modules\popsicle\package.json

$ npm install popsicle --save
$ typings install npm:popsicle
>> Error: You must specify a name for the dependency

$ typings install npm:popsicle --name popsicle
>> Error: Unable to resolve node_modules\blue-tape\package.json
```

**Comment by blakeembrey** [comment]
Awesome! Completing this issue (actually using `typings.json`) should solve this :+1: I'll do it today or tomorrow.

**Comment by jocull** [comment]
Thanks for all your help! I really appreciate the back and forth about this.

**Comment by blakeembrey** [comment]
My pleasure! I just released a patch with improved error messaging around what was going on. If you update and try again, it'll look like:

```
Error: Unable to read typings in "popsicle~native-or-bluebird". The author needs to add an entry to "typings.json" with the typings location
```

Hopefully that makes more sense for anyone running into the same thing!

**Comment by blakeembrey** [comment]
@jocull You can install the type definition using `typings` now! I added a `typings.json` and added all the dependencies to the `typings` registry for future users!
