### ISSUE TITLE
Out-of-the-box browser support missing from 2.x.x?

### ISSUE THREAD

**Issue by john-goldsmith** [blakeembrey/popsicle#34]
I noticed that [commit 8844172](https://github.com/blakeembrey/popsicle/commit/8844172e8dd370461d633ed7ceb4926d2b6ce7d4) removed `popsicle.js`, making `1.4.0` the last release with out-of-the-box browser support (unless I'm missing something).  This would seem to cause problems if installing and consuming via Bower.  If this is intentional, perhaps the documentation could be updated.

Thanks for Popsicle and your hard work!

**Comment by blakeembrey** [comment]
Thanks. I thought I had removed those instructions, but I can update it. Honestly, I can re-support it, but I hadn't realised anyone was actually using it since it required additional overhead to maintain but never had any specific issues. I intend to move to an attaching to GitHub releases structure, would that work for you?

**Comment by john-goldsmith** [comment]
Maybe my use case doesn't warrant the additional overhead (but I suppose it'd be nice if it did).  I'm using RAML along with your `raml-client-generator` Node package to create a JS SDK.  Part of this repo includes a demo HTML file that references the generated JS along with Popsicle, installed via Bower.

Per the README.md, running `bower install popsicle` fetches the latest 2.x.x release which only includes the TypeScript source and no distribution suitable for browsers.  This also appears to be true when installing via NPM -- is it possible to `require()` (CommonJS) or `import` (ES6) TypeScript files?.  I realize folks can run `npm run build`, but that's neither documented nor frictionless.  Lastly, The 2.x.x release no longer has a `bower.json` manifest, so I'm not even sure how installing via Bower still works.

**Comment by blakeembrey** [comment]
Actually, NPM only contains the JavaScript files and not the TypeScript source files. Only `require()` is possible on node, `import` is not implemented in either node or the browser.

I didn't say that Bower installing still works and I said I had forgotten to remove them, which I will now. If someone needed a Bower distribution though, I could include it or provide them with GitHub releases (preferable). If you use Bower, you should be able to point the location to zip in GitHub then.
