### ISSUE TITLE
PopsicleError class no longer exposed in 3.0.x

### ISSUE THREAD

**Issue by rgrove** [blakeembrey/popsicle#38]
Thanks for Popsicle! It's been a joy to use. :smile: 

In 2.0.x, the `PopsicleError` class was exposed at `require('popsicle').Error`, which was handy for doing `instanceof` checks. As of 3.0.0, it's no longer exposed there. Was this intentional?

It looks like I can still get the error class with `require('popsicle/dist/error')`, but that feels a bit like I'm poking around in innards that might change. What would you recommend?

**Comment by blakeembrey** [comment]
Not intentional to block access to this, I'll re-expose it.

**Comment by blakeembrey** [comment]
https://github.com/blakeembrey/popsicle/releases/tag/v3.0.3 :+1:

**Comment by rgrove** [comment]
Awesome. Thanks!
