### ISSUE TITLE
Dependent typings not resolving in compilation

### ISSUE THREAD

**Issue by amcdnl** [blakeembrey/popsicle#39]
so when I install the typings for this project, I get errors from child typings inside popsicle not resolving.

**typings.json**
```
{
  "dependencies": {
    "popsicle": "npm:popsicle"
  }
}
```

***typings install output***
```
i:node austin$ typings install

├─┬ popsicle
│ ├── arrify
│ ├── concat-stream
│ ├── form-data
│ ├── infinity-agent
│ ├─┬ make-error-cause
│ │ └── make-error
│ ├── methods
│ ├─┬ native-or-bluebird
│ │ └── es6-promise
│ ├── tough-cookie
│ └── xtend
```

then when i run `tsc` I get:

```
node austin$ tsc

1 import makeErrorCause = require('make-error-cause');
                                  ~~~~~~~~~~~~~~~~~~

node_modules/popsicle/dist/error.d.ts(1,33): error TS2307: Cannot find module 'make-error-cause'.


1 import Promise = require('native-or-bluebird');
                           ~~~~~~~~~~~~~~~~~~~~

node_modules/popsicle/dist/index.d.ts(1,26): error TS2307: Cannot find module 'native-or-bluebird'.


1 import { CookieJar } from 'tough-cookie';
                            ~~~~~~~~~~~~~~

node_modules/popsicle/dist/jar.d.ts(1,27): error TS2307: Cannot find module 'tough-cookie'.


1 import Promise = require('native-or-bluebird');
                           ~~~~~~~~~~~~~~~~~~~~

node_modules/popsicle/dist/request.d.ts(1,26): error TS2307: Cannot find module 'native-or-bluebird'.


1 import makeErrorCause = require('make-error-cause');
                                  ~~~~~~~~~~~~~~~~~~

node_modules/popsicle/dist/error.d.ts(1,33): error TS2307: Cannot find module 'make-error-cause'.


1 import Promise = require('native-or-bluebird');
                           ~~~~~~~~~~~~~~~~~~~~

node_modules/popsicle/dist/index.d.ts(1,26): error TS2307: Cannot find module 'native-or-bluebird'.


1 import { CookieJar } from 'tough-cookie';
                            ~~~~~~~~~~~~~~

node_modules/popsicle/dist/jar.d.ts(1,27): error TS2307: Cannot find module 'tough-cookie'.


1 import Promise = require('native-or-bluebird');
                           ~~~~~~~~~~~~~~~~~~~~

node_modules/popsicle/dist/request.d.ts(1,26): error TS2307: Cannot find module 'native-or-bluebird'.


32   async cypher(statement: string, parameters: any = {}) {
           ~~~~~~
```

Shouldn't it resolve those automatically for me?

**Comment by blakeembrey** [comment]
Actually, it does. If you look in the compiled `typings/main/definitions/popsicle/popsicle.d.ts` you'll see it's correct. I need to workaround (hack) this from the compiler, the relevant issue is https://github.com/Microsoft/TypeScript/issues/6427.

**Comment by dmikov** [comment]
Actually, it doesn't. In terms, that it doesn't copy other definitions into the typings folder.
For instance even though the typings.json calls for all of the above modules, the d.ts files are missing from in typings/definition folder

**Comment by blakeembrey** [comment]
@dmikov Actually, it does. It's how Typings has worked since I originally wrote it.

![image](https://cloud.githubusercontent.com/assets/1088987/12727013/9a2d6058-c8cf-11e5-9966-35b949c32a7e.png)

**Comment by Davste93** [comment]
Any updates on this one?

**Comment by blakeembrey** [comment]
Yes, I understand. I would like it to work for myself too :smile: Watch out for Typings@0.7, I'm going to try doing a simpler intermediate patch to fix the use-case of native "Typings" libraries.

**Comment by Davste93** [comment]
Thanks! Right now I'm facing the sitiuation where `moduleResolution:node` breaks popsicle and `moduleResolution:classic` breaks angular 2.

**Comment by blakeembrey** [comment]
Yeah, I completely understand. I'm in the same boat, and have been for a long time - just didn't have time to properly patch it. I think I just got to it though, so there should be a 0.7 release for next week that patches this.

**Comment by blakeembrey** [comment]
If you install `typings@0.7`, this should now be resolved. If it is not, please open an issue in Typings.

**Comment by dowrow** [comment]
This is awful. Why can't I compile the same angular2 app after updating node and npm to the latest version? Why would typings install fail with a  "Cannot find module 'popsicle'"?
Really thinking about switching from angular2 to React only to not mess with this shit anymore. Our code base is basically uncompilable now due to this change.

**Comment by blakeembrey** [comment]
@dowrow Please create an issue. I have no desire to help someone who just comments on a random thread with complaints but gives no issue and complains about completely unrelated things - whether you use Angular 2 or React is unrelated, I've never even used Angular 2 myself.
