### ISSUE TITLE
native-or-bluebird is deprecated. please switch to any-promise

### ISSUE THREAD

**Issue by jonathanong** [blakeembrey/popsicle#40]
https://github.com/kevinbeaty/any-promise

this implementation supports more promise implementations and allows the end-user to configure the promise implementation.

**Comment by blakeembrey** [comment]
Released `v3.1.1` with `any-promise` :+1: Any word when https://github.com/thenables/thenify will be updated to match?

**Comment by jonathanong** [comment]
done :)

**Comment by blakeembrey** [comment]
Awesome, cheers! I have to narrow it down, but this set of changes actually broke caching of HTTP requests since it's using promises to resolve internally (no idea how, I can only assume a `Promise.resolve` was imploding with this mix and match).
