### ISSUE TITLE
Limit simultaneous requests

### ISSUE THREAD

**Issue by mtt87** [blakeembrey/popsicle#45]
Is there a way to limit simultaneous requests?

I've tried to set this but doesn't seem to have any effect:
```
import request from 'popsicle';
import auth from 'popsicle-basic-auth';
import http from 'http';
http.globalAgent.maxSockets = 10;
```

Any suggestion ? :smile: 

Thanks!

**Comment by blakeembrey** [comment]
Not built in, but we could publish a plugin. The relevant logic is pretty much: https://github.com/blakeembrey/popsicle-limit/blob/master/popsicle-limit.js#L9-L13. Just make a `before` wrapper that limits the number of concurrent requests running.

**Comment by mtt87** [comment]
I've temporarily solved using https://github.com/ForbesLindesay/throat but in 2 weeks when I'm back from hols I'll see if I can build a plugin :+1:

**Comment by blakeembrey** [comment]
I've added `throat` to the README: https://github.com/blakeembrey/popsicle#helpful-utilities. It's a great solution and easily re-usable in other places.
