### ISSUE TITLE
Type defs not found on typings

### ISSUE THREAD

**Issue by jocull** [blakeembrey/popsicle#54]
I searched for Popsicle, but nothing came up:

```
$ typings search popsicle
> No results found for search
```

However, when installing with the syntax listed in the README everything is fine:

```
$ typings install npm:popsicle -S
popsicle@5.0.1
├─┬ any-promise
│ └── es6-promise
├── arrify
├── concat-stream
├── form-data
├─┬ make-error-cause@1.1.0
│ └── make-error
├── methods
├── tough-cookie
└── xtend
```

Why? I didn't see any mention of the `install npm:package` syntax (as opposed to `install npm~package`) in the typings docs, so it feels like this is a bit cryptic.

**Comment by blakeembrey** [comment]
Why did you open an issue here? They are both documented commands in Typings, Popsicle does not existing on the Typings registry because it's already a TypeScript project. See https://github.com/typings/typings/blob/master/docs/commands.md#install.

**Comment by jocull** [comment]
Sorry about that! First day with Typings from TSD and I knew you were behind both projects. Hadn't seen the `npm:` syntax used anywhere else and missed the subtlety in the docs.

Thanks for the quick response, all the same!

**Comment by blakeembrey** [comment]
No worries, it's definitely a bit of an ugly part - but it's sadly the only way to achieve compatibility with _everything_ everywhere. For reference, the `~` (previously `!`) is just a shorthand for `registry:<source>/<pkg>`.
