### ISSUE TITLE
how can I use it in browser

### ISSUE THREAD

**Issue by yongpingchen** [blakeembrey/popsicle#56]
Should I build this repository by myself to generate a JS file for browser use case?

**Comment by blakeembrey** [comment]
Do you currently use a bundler like Webpack or Browserify?

**Comment by yongpingchen** [comment]
I am developing a library, and using Webpack, which can generate UMD package for my library. And my finally released library must not include popsicle bundle. 

I am considering to use popsicle in my library, but confuse how to import popsicle together with my library when my library consumer developing browser project.

**Comment by blakeembrey** [comment]
If you're using Webpack, it should just work unless you disabled browser resolution (https://webpack.github.io/docs/configuration.html#resolve-packagemains).

**Comment by blakeembrey** [comment]
What is the issue you're having? Can you post an error or anything else?

**Comment by yongpingchen** [comment]
@blakeembrey thanks for reply. The issue I am facing is: my UMD library built with Webpack doesn't include popsicle, so my library consumers need to include popsicle by themselves. Does popsicle has built JS file somewhere, so that they can use it directly. If not, how can they do it?

**Comment by blakeembrey** [comment]
Sure, it's just built using Browserify (https://github.com/blakeembrey/popsicle/blob/master/package.json#L22). You can access a Browserified build from this service: https://wzrd.in/standalone/popsicle@latest

**Comment by blakeembrey** [comment]
I can also try updating the release process to build modules in GitHub releases.

**Comment by yongpingchen** [comment]
Thanks @blakeembrey you help me lot.
