### ISSUE TITLE
error TS2307: Cannot find module 'url'.

### ISSUE THREAD

**Issue by yongpingchen** [blakeembrey/popsicle#57]
I am using popsicle in my typescript project. And following the steps in README: 

- install by npm
```
$ npm install popsicle 
```
- install declaration file by typings
```
$ typings install npm:popsicle
```
- reference to my ts file( `src/MyRequest.ts`)

```ts
/// <reference path="../typings/modules/popsicle/index.d.ts" />
import {request as Popsicle} from 'popsicle'
```

- compile error
```
$ tsc src/MyRequest.ts
```
  with the following error:
```
typings/modules/popsicle/index.d.ts(82,21): error TS2307: Cannot find module 'url'.
```
And problem part of `index.d.ts` code like this:

```ts
...
// Source: node_modules/popsicle/dist/base.d.ts
declare module '~popsicle/dist/base' {
import { Url } from 'url';                                               // problem here
export interface Query {
    [key: string]: string | string[];
}
export interface Headers {
    [name: string]: string | string[];
}
export type RawHeaders = string[];
export interface BaseOptions {
    url?: string;
    query?: string | Query;
    headers?: Headers;
    rawHeaders?: RawHeaders;
}
export default class Base {
    Url: Url;
    rawHeaders: RawHeaders;
    constructor({url, headers, rawHeaders, query}: BaseOptions);
    url: string;
    query: string | Query;
    headers: Headers;
...
```

tsc version: **Version 1.8.10**
typings version: **1.3.1**

**Comment by yongpingchen** [comment]
complete typings file
[popsicle.zip](https://github.com/blakeembrey/popsicle/files/340689/popsicle.zip)

**Comment by blakeembrey** [comment]
It expects a global `url` to exist. This isn't an error. You need a global URL module - it's usually bundled automatically with Browserify, Webpack or node.

**Comment by yongpingchen** [comment]
How can I do it. I tried with the following way, but did not work:

```
npm install url
typings install dt~url #error thrown, since not typings for url
```

**Comment by blakeembrey** [comment]
You can get  it from `node` - what's the error that persists there?

**Comment by yongpingchen** [comment]
> You can get it from `node`

Did you mean to install typings of `node` by 
```
npm install node
typings install dt~node --global 
```
I did it, and declaration file of node can be found as 'typings/global/node/index.d.ts'. However, when I compile my `src/MyRequest.ts` again, error still there: 

```
typings/modules/popsicle/index.d.ts(82,21): error TS2307: Cannot find module 'url'.
```

Did I miss something?

**Comment by blakeembrey** [comment]
It should work. I'm guessing you haven't included the file in the TypeScript project. Can you share how you're running compilation?

**Comment by yongpingchen** [comment]
@blakeembrey thanks for your hint. I include `"typings/globals/node/index.d.ts"` to `"files"` section of `tsconfig.json`, then compile succeeded.  Like this

```
# tsconfig.json
    "files": [
        "src/MyRequest.ts",
        "typings/globals/node/index.d.ts"
    ]
```

I am wondering why it needs to do it? Shouldn't it automatically find it?

**Comment by blakeembrey** [comment]
No, you would either be using `tsconfig.json` with exclude or files. If you're using files, you need to include the files manually. If you're using exclude, it just includes every `.{ts,tsx}` file it finds. There's some docs in https://github.com/typings/typings/blob/master/docs/faq.md#module-resolutions, but it could be made more prominent.

**Comment by yongpingchen** [comment]
I see. 

> but it could be made more prominent.

Totally agree. I will helpfull especially for  beginner :D
