### ISSUE TITLE
Parser can not handle 204 case well

### ISSUE THREAD

**Issue by yongpingchen** [blakeembrey/popsicle#66]
From version v8.0.0, need to define response parser, by calling`use(popsicle.plugins.parse([...]))`. 
However, for `PUT`, or `DELETE`, usually the successful response is 204 code without response body. And for failure response, usually with json type response body. 

If I don't define response parser, for succeeded response is ok. But need to manually parse string type of failure response. 

I think need to improve [this line of code](https://github.com/blakeembrey/popsicle/blob/master/lib/plugins/common.ts#L109) by confirm status code wether is 204

**Comment by blakeembrey** [comment]
It's not 204, but an empty body. Ideally you wouldn't try to parse a body that'll be empty (making it consistent) but we could add something to handle `body == null || body === ''`.
