### ISSUE TITLE
How to prevent the lib to send an OPTIONS request before GET, PUT, POST

### ISSUE THREAD

**Issue by vitorleal** [blakeembrey/popsicle#74]
Hi,
im having a problem with this because the API im using don't implement the `OPTIONS` type and it returning an `"EUNAVAILABLE"` for me.

Thanks

**Comment by vitorleal** [comment]
Sorry problem with CORS

**Comment by blakeembrey** [comment]
No worries 😄 Sadly, in the browser, it's impossible to tell the difference between a CORS-blocked request and a regular failing request. I'd love to improve that error message.
