### ISSUE TITLE
add types property to package.json for typescript 2.0

### ISSUE THREAD

**Issue by hodavidhara** [blakeembrey/popsicle#75]
Trying to use popsicle with typescript 2.0 gave me the error: `test.ts (1,22): Cannot find module 'popsicle'. (2307)`

According to https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html it seem like a `types` or `typings` property needs to be added.

**Comment by blakeembrey** [comment]
No thanks. You need to use Typings to install the module. I'll be happy to use TypeScript `@types` once they support redirects.
