### ISSUE TITLE
Popsicle violates HTTP spec with User-Agent header

### ISSUE THREAD

**Issue by Malvineous** [blakeembrey/popsicle#87]
I've been trying to narrow down a problem where Popsicle is unable to talk to a HTTP server and it looks like the reason is that Popsicle is sending an invalid value in the HTTP `User-Agent` header.

According to the [RFC](https://tools.ietf.org/html/rfc7231#section-5.5.3), the user agent must be a string of tokens and comments, and a token is [defined](https://tools.ietf.org/html/rfc7230#section-3.2.6) as something that does not contain delimiters, one of which is a colon.  So because Popsicle is setting the `User-Agent` to the URL of the project page and this has a colon in it, it is in violation of the HTTP spec, which causes the server to reject the request.

Colons are allowed in HTTP header comments, which are strings surrounded with parentheses.  So putting the URL in brackets will fix the problem.

Can I request that the default `User-Agent` be changed to something like `Popsicle (http://blah)` instead?

**Comment by blakeembrey** [comment]
That seems like a good idea, thanks for the reference. Looks like I've erroneously copied this from `got` when I needed to add a default header (for compact with APIs like GitHub's which block otherwise).

**Comment by blakeembrey** [comment]
Thanks again for the report! Fixed in `9.1.0`.

**Comment by Malvineous** [comment]
Perfect!  Many thanks.
