### ISSUE TITLE
[Request] Add `typings` field to package.json

### ISSUE THREAD

**Issue by TylorS** [blakeembrey/popsicle#88]
First of thanks for taking the time to create and maintain this library!

I was wondering if it would be possible to add the `typings` field to the package.json in order to allow those who are not using `typings` to make use of the typescript definitions built with the library. If it would be accepted, I'd gladly make the PR required.

**Comment by blakeembrey** [comment]
It can't be done because of the dependencies, check the couple of existing issues.
