### ISSUE TITLE
TypeScript Declaration Publishing

### ISSUE THREAD

**Issue by delight-by** [blakeembrey/popsicle#90]
See [TypeScript Declaration Publishing](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)

Right now VS Code doesn't automatically load bundled TypeScript definitions. Either two of the options from the link above should solve the problem.

I've only checked adding `types: "./dist/common.d.ts"` property to `package.json` and it kind of worked (but still throwing errors about tough-cookie).

**Comment by blakeembrey** [comment]
Please search existing issues before opening a new one. I know how it all works, I'm stuck with a lack of TypeScript supporting what I need to make it work. See https://github.com/Microsoft/types-publisher/issues/4 and https://github.com/Microsoft/TypeScript/issues/7753, with duplicate issues being https://github.com/blakeembrey/popsicle/issues/89, https://github.com/blakeembrey/popsicle/issues/88 and  https://github.com/blakeembrey/popsicle/pull/77.

**Comment by delight-by** [comment]
Sorry, my bad, should have looked into closed issues first. Went with typings after all.

**Comment by blakeembrey** [comment]
Sorry for the pain, I know it's annoying! I wish I could replace Typings today too, but I need to get all the dependencies into DefinitelyTyped and even then, I can't support browser module resolution in case anyone is using `popsicle` in browsers.
