### ISSUE TITLE
package.json does not contain typings but dist has all d.ts files

### ISSUE THREAD

**Issue by AllNamesRTaken** [blakeembrey/popsicle#92]
Adding popsicle npm package and then importing using 
```
import popsicle from 'popsicle'
```
causes squiggles in vscode since it doesnt find the definition file, although it is included as common.d.ts
Simply adding 
```
"typings": "dist/common.d.ts",
``` 
solves this.

Is there a reason why this is not included?

**Comment by blakeembrey** [comment]
Please search existing issues and PRs for the answer.
