### ISSUE TITLE
How to use within a Browser?

### ISSUE THREAD

**Issue by bennyn** [blakeembrey/popsicle#96]
Popsicle states that it works on node and the browser but I couldn't find documentation on how to run it on the client-side. I did `bower install popsicle` and looked for something like `popsicle.js` or `popsicle.min.js` but there is no such file. 😢 

Can you please give a small example on how to use Popsicle within a web browser?

**Comment by blakeembrey** [comment]
Do you use Webpack or Browserify? If you do, all you need to do is require it.

**Comment by bennyn** [comment]
No, I don't use webpack or browserify.

**Comment by blakeembrey** [comment]
You would have to build it yourself then. I don't build a single `.js` file anymore because it's a pain to maintain. You can see how I build it in https://github.com/blakeembrey/popsicle/blob/fa47bd475f89ea69d4d3b8b82d68e36c883c4f33/package.json#L22.

**Comment by bennyn** [comment]
Oh, that's very inconvenient. I will be using `axios` then.

**Comment by blakeembrey** [comment]
Sure, go for it. You will find yourself often in this situation if you intend to go the bower and pre-built libraries only route. Not to mention that you'll be relying on their bundling and minification techniques instead of your own, which will probably end up much less optimised as a result.
